services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001

volumes:
  minio_data:
