version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "80:9000"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    command: server /data

volumes:
  minio_data: