name: Deploy to EC2 and Restart Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -r -o StrictHostKeyChecking=no ./* ubuntu@44.203.237.159:/home/gma

    - name: Restart Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@44.203.237.159 << 'EOF'
        cd /home/gma
        docker-compose down
        docker-compose up -d
        EOF